version: '3.4'

services:
  postgres:
    image: postgres
    container_name: db
    environment:
      POSTGRES_PASSWORD: "postgresspass"
    ports:
      - 5432:5432
  rabbit:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 15672:15672