FROM golang:1.21-alpine3.18 as build-stage

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN CGO_ENABLED=0 GOOS=linux 
RUN go build -o service cmd/api/*.go

FROM alpine:3.18 AS build-release-stage


COPY --from=build-stage /app/service .

EXPOSE 8080

CMD [ "./service" ]


